#!/bin/bash

function prep()
{
    chmod a-x "$1"
    dos2unix -q "$1"
    git add "$1"
    echo "$1"
}

case $# in
    0 ) set - *.md */*.md pom.xml */pom.xml src */src ;;
esac

git status "$@" -s | \
    while read S f arrow g
do
    case $S in
        D ) ;;
        R* ) prep "$g" ;;
        * ) prep "$f" ;;
    esac
done
