#!/bin/bash

# This is free and unencumbered software released into the public domain.
#
# Please see https://github.com/binkley/binkley/blob/master/LICENSE.md.

read -er -p 'Passphrase: ' gpg_passphrase
echo # Get back newline
GPG_PASSPHRASE="$gpg_passphrase" exec "$@"
